spring:
  application:
    name: dividend  # 애플리케이션 이름 설정

  datasource:
    driver-class-name: org.h2.Driver  # H2 드라이버 클래스 이름
    url: jdbc:h2:mem:zerobase;DB_CLOSE_DELAY=-1  # H2 메모리 데이터베이스 URL
    username: sa  # 데이터베이스 사용자 이름
    password:  # 데이터베이스 비밀번호

  jpa:
    hibernate:
      ddl-auto: create
      use-new-id-generator-mappings: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  h2:
    console:
      enabled: true  # H2 콘솔 활성화
      path: /h2-console  # H2 콘솔 경로 설정

logging:
  level:
    root: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
